spring:
  redis:
    cluster:
      nodes: 192.168.31.125:7000,192.168.31.125:7001,192.168.31.126:7000,192.168.31.126:7001,192.168.31.127:7000,192.168.31.127:7001
    password:
    # 连接超时时间（毫秒）
    timeout: 10000ms
  #    database: 0
  #    host: 192.168.1.144
  #    port: 7000
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://192.168.1.151:8761/eureka
ssoUrl: http://192.168.1.151:8082