spring:
  datasource:
    url: jdbc:sqlserver://192.168.1.31;DatabaseName=workflow
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: sa@12345
eureka:
  client:
    service-url:
      defaultZone:  http://192.168.1.151:8761/eureka
tx-lcn:
  ribbon :
    loadbalancer.dtx.enabled: true
  # 默认之配置为TM的本机默认端口
  client:
    manager-address: 192.168.0.8:8070