spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.8:13306/tx-manager?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  redis:
    # 连接超时时间（毫秒）
    timeout: 10000ms
    host: 192.168.0.8
    port: 6379
    password: nasoft2021
tx-lcn:
  manager:
    host: 192.168.0.8
    #
    port: 8070
    concurrent-level: 128
    admin-key: codingapi
    ex-url-enabled: false
  message:
    netty:
      attr-delay-time: 10000
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
#eureka:
#  client:
#    service-url:
#      defaultZone:  http://192.168.1.177:8761/eureka
